# To debug : https://auth.default.pewty.xyz/api/v3/admin/system/

authentik:
  secret_key: ${SECRET_KEY}
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.beryju.org, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    host: ${AUTHENTIK_IP}
    port: ${AUTHENTIK_PORT}
    name: ${AUTHENTIK_NAME}
    user: ${AUTHENTIK_USER}
    password: ${AUTHENTIK_PASSWORD}

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: ${DOMAIN}
      paths:
        - path: "/"
          pathType: Prefix

postgresql:
  enabled: false
redis:
  enabled: true
  master:
    persistence:
      storageClass: "scw-bssd"

env:
  CSRF_TRUSTED_ORIGINS: 
    - https://${DOMAIN}
