vmsingle:
  enabled: false

vmcluster:
  enabled: true
  spec:
    retentionPeriod: "365"
    vmstorage:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "scw-bssd"
            resources: 
              requests:
                storage: "20Gi"
    vmselect:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "scw-bssd"
            resources: 
              requests:
                storage: "2Gi"

alertmanager:
  spec:
    externalURL: "https://${ALERTMANAGER_DOMAIN}"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "scw-bssd"
          resources: 
            requests:
              storage: "2Gi"
  ingress:
    enabled: false
    ingressClassName: "traefik"
    hosts:
    - ${ALERTMANAGER_DOMAIN}

grafana:
  persistence:
    enabled: true
    storageClassName: "scw-bssd"
  ingress:
    enabled: true
    ingressClassName: "traefik"
    hosts:
    - ${GRAFANA_DOMAIN}
  env:
    GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
    GF_AUTH_GENERIC_OAUTH_NAME: "${GRAFANA_OAUTH_APP}"
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "${GRAFANA_OAUTH_CLIENT_ID}"
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${GRAFANA_OAUTH_CLIENT_SECRET}"
    GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://${GRAFANA_OAUTH_DOMAIN}/application/o/authorize/"
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://${GRAFANA_OAUTH_DOMAIN}/application/o/token/"
    GF_AUTH_GENERIC_OAUTH_API_URL: "https://${GRAFANA_OAUTH_DOMAIN}/application/o/userinfo/"
    GF_AUTH_SIGNOUT_REDIRECT_URL: "https://${GRAFANA_OAUTH_DOMAIN}/application/o/${GRAFANA_OAUTH_GF_APP}/end-session/"
    # Optionally enable auto-login (bypasses Grafana login screen)
    GF_AUTH_OAUTH_AUTO_LOGIN: "true"
    # Optionally map user groups to Grafana roles
    GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'Grafana Admin') && 'Admin' || contains(groups[*], 'Grafana Editor') && 'Editor' || 'Viewer'"
  grafana.ini:
    server:
      root_url: https://${GRAFANA_DOMAIN}
kubeEtcd:
  enabled: false
