apiVersion: v1
kind: Secret
metadata:
  name: scaleway-secret
  namespace: kube-system
type: Opaque
data:
    SCW_ACCESS_KEY: ${SCW_ACCESS_KEY}
    SCW_SECRET_KEY: ${SCW_SECRET_KEY}
    SCW_DEFAULT_PROJECT_ID: ${SCW_DEFAULT_PROJECT_ID}
    SCW_DEFAULT_ZONE: ${SCW_DEFAULT_ZONE}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: default
type: Opaque
data:
    username: ${GITEA_USERNAME}
    password: ${GITEA_PASSWORD}
    email: ${GITEA_EMAIL}
---
